### ISSUE TITLE
searchPatients does not return the patient when I search using phone number

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-backend#1]
I registered using my phone number (UserId = 118 - you can get the phone number from the db for replicating this). I then used my registered phone number in the searchPatients API call as the phoneNumber parameter (98942xxxxx - not shown here for privacy). The API returned 0 results. It should have returned a match.

**Comment by SyedQantler** [comment]
This has been completed with below commit:
c04debc560c69dacf42e969d4bd6eaad98aa94d1
