### ISSUE TITLE
searchPatient API - medicalRequestStatus parameter not being returned, healthRequestStatus needs to be renamed to healthAlert

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-backend#10]
PatientStatus table has two relevant fields that should be returned by patientStatus API call. They are:
- medicalRequestStatus - if the patient submitted a request from the Need Help (formerly Raise your hand) tab.
- healthAlertStatus - if the patient showed any symptoms of COVID in their health update that they submit once of twice a day.

Here's one of the return values from searchPatient API call:

        {
            "patientID": 266,
            "firstName": "Kelvin",
            "lastName": "Spence",
            "householdId": null,
            "covid19Status": "Recovered",
            "quarantineStatus": "Quarantined",
            "isolationStatus": "Isolation ended",
            "healthRequestStatus": "false",
            "quarantineRequestStatus": "Open",
            "suppliesRequestStatus": "Open",
            "geofenceStatus": null,
            "heartbeatStatus": "Online",
            "latitude": 32.82695770263672,
            "longitude": 0.0
        },

It turns out that when I specify the medicalRequestStatus input parameter in the API call, it searches the correct field. But the return value puts the value of the healthAlertStatus in a repsonse parameter called 'healthRequestStatus'. 

There seems to be a bug in line 113 in com.covid.repository.[PatientDao.java](https://github.com/covenantproject/cov-backend/blob/98e385129ff1c8f32049d0557fcef6725b93427a/src/main/java/com/covid/repository/PatientDao.java#L22):

            dto.setHealthRequestStatus(rs.getString("HealthStatusAlert"));

The response should not have a parameter called 'healthRequestStatus'. Instead, it should have these two parameters:

1. healthRequestStatus (from HealthRequestStatus column)
2. healthStatusAlert (from HealthStatusAlert column)

Thanks!

**Comment by sencode** [comment]
I tested the service today and found some issues:

1.  Response is still not returning medicalRequestStatus parameter. It still returns:
 "healthRequestStatus": null, 
for all patients. Please correct this.

2. Request parameter healthStatusAlert is named as healthAlertStatus. I can see why this is confusing. Please change this to healthAlert in both request and response so that it is not confusing to both backend and dashboard developers.

Please fix, retest and deploy on test server after it passes your tests.

**Comment by SyedQantler** [comment]
This is fixed with the commit  - 26be20f3eb1a6dc4facfe1f88218448780991a56
