### ISSUE TITLE
searchPatient API - pleasee add geofenceCompliant input/output parameter

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-backend#11]
searchPatient API currently has genfenceStatus input/output parameter. In addition to this, please add another input/output parameter named geofenceCompliant.

geofenceCompliant is a boolean parameter. It maps to PatientStatus.geofenceStatus as follows:

if geofenceStatus = 'Inside' then geofenceCompliant = 'true'
if geofenceStatus = 'Outside - near' or geofenceStatus = 'Outside - far', then geofenceCompliant = 'false'

This helps the dashboard user to filter which patients are compliant and which ones are not. This is needed since the input parameter geofenceStatus only accepts a single value, but there are two possible values for non-compliance.

**Comment by sentran** [comment]
FYI, 'Geofence - far' is defined as more than 1km outside the geofence area.

**Comment by sencode** [comment]
I tested the latest version today. It is not working as expected. 

I get the same responses whether I I query with either geofenceCompliant = true or geofenceCompliant = false. This is not correct.

Among these results:

        {
            "patientID": 265,
             ... 
            "geofenceStatus": "**Inside**", 
            "geofenceCompliant": **true**, **// correct**
             ... 
        },

        {
            "patientID": 50,
             ... 
            "geofenceStatus": **null**,
            "geofenceCompliant": **true**, // **INCORRECT, this should also be null**
             ... 
        },

        {
            "patientID": 272,
             ... 
           "geofenceStatus": "**Outside - near**",
            "geofenceCompliant": **true**, //**INCORRECT, this should be false**
             ... 
        },

        {
            "patientID": 274,
             ... 
            "geofenceStatus": "**Outside - far**",
            "geofenceCompliant": **true**, // **INCORRECT, this should be false**
             ... 
        },

If geofenceStatus is null, then geofenceCompliant should also be null
If geofenceStatus is 'Outside - near' then geofenceCompliant should be false
If geofenceStatus is 'Outside - far' then geofenceCompliant should be false
If geofenceStatus is 'Inside' then geofenceCompliant should be true

If I query for geofenceCompliant = false, then the service **should not** return patients with geofenceCompliant = true, and vice versa.

**Comment by SyedQantler** [comment]
This is fixed with the commit - b09fbd53eeca4757f36de4dfda29b6e4984b6000
