### ISSUE TITLE
Question/clarification on creating health professional user accounts on the dashboard

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-backend#7]
Currently, the dashboard user accounts are created on KeyCloak. However, the health professionals who use the dashboard need to have their own rows in the User and HealthProfessionals in the database. I discussed this with Samy on the phone, and here is the workflow we came to an agreement on:

1. User manager account will be manually created in KeyCloak 

2. User manager logs on to Dashboard using thei username and password from keycloak

3. User manager clicks on a 'Create New Health Professional" button in the dashboard, fills our pertinent information (Name, email, phone number, assigned location and assigns the groups)
- The two groups available are 'HealthProfessionals' and 'UserManagers '

4. On submitting the form, two things happen:
- First, call the createUser-Keycloak API call to create a new user account (with email activation)

- On success of the first (keycloak) API call, the dashboard will call the registerNewHealthPro to create a new user/healthpro in our database - rows will be created in both User and HealthProfessional tables. 

5. The newly created user can then activate their account using the activation email, set a password and then login to the dashboard using the new credentials. They can then find and view their assigned patients.

Please confirm if the above workflow sounds good. If yes, the following action items need to be done:

1. Qantler team to add specs for an API call to create a new user in KeyCloak. 
2. Qantler team to add a username field to the User table, and add the username field as an input parameter to the registerNewHealthPro API call. 
3. Qantler team to verify that the registerNewHealthPro API call will add appropriate rows in the User, HealthProfessional, PhoneNumber, EmailAddress and Address tables for the new health professional.

**Comment by SyedQantler** [comment]
The changes are completed with the below commit
e190408226ccdaaf77e5cbef69840ef4da8cd75a

Keycloak user creation is updated in postman under CreateUser -Keycloak API
