### ISSUE TITLE
getPatientInfo returns error 500

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-backend#9]
{{baseurl}}/getPatientInfo?patientId=271
returns:
{
    "timestamp": "2020-05-03T19:23:40.047+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "org.hibernate.PropertyAccessException: Null value was assigned to a property [class com.covid.model.Patient.HasInternationalTravel] of primitive type setter of com.covid.model.Patient.HasInternationalTravel",
    "path": "/covid_service/web/api/getPatientInfo"
}

{{baseurl}}/getPatientInfo?patientId=265
returns:
{
    "timestamp": "2020-05-03T19:27:43.863+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "org.hibernate.PropertyAccessException: Null value was assigned to a property [class com.covid.model.Patient.HasInterstateTravel] of primitive type setter of com.covid.model.Patient.HasInterstateTravel",
    "path": "/covid_service/web/api/getPatientInfo"
}

HasInternationalTravel and HasInterstateTravel are optional fields. If the error is because the field is null in the database, the API should return that without throwing an error.

**Comment by sencode** [comment]
Update from Qantler team: HasInternationalTravel and HasInterstateTravel have been set to optional fields. Now the API errors off when a patient has more than one address. Discussed multiple options with Qantler team. Here's the proposed solution:

1. In the interest of time, if a patient has multiple addresses, the API will return the address with max(AddressId) - since that is the most recent address entered into the system.

2. Later on, we will allow the patients with multiple addresses to select one of them as the quarantine address and allow them to save it in the database. This technical debt is recognized and will be addressed later.

**Comment by SyedQantler** [comment]
Fixed to return topmost address(in case of multiple addresses) as per the latest conversation. Fixed other issues as well with the commit - 26be20f3eb1a6dc4facfe1f88218448780991a56
